version: '3.8'

services:
  # The Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: habit_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habits
    ports:
      - "5432:5432"

  # The Cache (Redis)
  cache:
    image: redis:7-alpine
    container_name: habit_cache
    ports:
      - "6379:6379"
      